package baza;

public class Rekordy {

	public static void addData() {
		Baza z = new Baza();
		z.insertStawka("2x805Na", 13.48);
		z.insertStawka("1x805Na", 8.76);
		z.insertStawka("Niskopod≥ogowy", 16.78);
		z.insertStawka("Helmut", 8.56);
		z.insertOdcinek("Aleksandrowska", "KOCHAN”WKA-TEOFIL”W", 0.8f, 4);
		z.insertOdcinek("Aleksandrowska", "TEOFIL”W-DW.£”Dè ØABIENIEC", 3, 11);
		z.insertOdcinek("Limanowskiego", "DW.£”Dè ØABIENIEC-W≥Ûkniarzy", 0.8f, 1);
		z.insertOdcinek("Limanowskiego", "W≥Ûkniarzy-Zachodnia", 2, 8);
		z.insertOdcinek("Zgierska", "Targowisko Dolna-HELEN”WEK", 4.7f, 16);
		z.insertOdcinek("Warszawska", "Targowisko Dolna-MARYSIN WARSZAWSKA", 4, 17);
		z.insertOdcinek("Zachodnia", "Limanowskiego-Targowisko Dolna", 0.35f, 2);
		z.insertOdcinek("Zgierska", "Limanowskiego-Targowiska Dolna", 0.45f, 2);
		z.insertOdcinek("Limanowskiego", "Zachodnia-Zgierska", 0.2f, 2);
		z.insertOdcinek("W≥Ûkniarzy", "SrebrzyÒska-Limanowskiego", 2.2f, 7);
		z.insertOdcinek("W≥Ûkniarzy", "LegionÛw-SrebrzyÒska", 0.5f, 2);
		z.insertOdcinek("Zachodnia", "Ogrodowa-Limanowskiego", 1, 5);
		z.insertOdcinek("Zgierska", "Wojska Polskiego-Limanowskiego", 0.35f, 2);
		z.insertOdcinek("Nowomiejska", "PLAC WOLNOåCI-Wojska Polskiego", 0.75f, 6);
		z.insertOdcinek("Wojska Polskiego", "Zgierska-FranciszkaÒska", 0.5f, 2);
		z.insertOdcinek("Wojska Polskiego", "FranciszkaÒska-STRYKOWSKA", 2.7f, 10);
		z.insertOdcinek("FranciszkaÒska", "PÛ≥nocna-Wojska Polskiego", 0.55f, 2);
		z.insertOdcinek("Ogrodowa", "Zachodnia-Nowomiejska", 0.15f, 1);
		z.insertOdcinek("Zachodnia", "LegionÛw-Ogrodowa", 0.25f, 1);
		z.insertOdcinek("KiliÒskiego", "Pomorska-PÛ≥nocna", 0.25f, 2);
		z.insertOdcinek("SrebrzyÒska-Cmentarna", "KOZINY-LegionÛw", 1.5f, 5);
		z.insertOdcinek("LegionÛw", "Cmentarna-GdaÒska", 0.3f, 2);
		z.insertOdcinek("LegionÛw", "GdaÒska-Zachodnia", 0.3f, 2);
		z.insertOdcinek("LegionÛw", "Zachodnia-PLAC WOLNOåCI", 0.2f, 1);
		z.insertOdcinek("Pomorska", "PLAC WOLNOåCI-KiliÒskiego", 0.5f, 3);
		z.insertOdcinek("Pomorska", "KiliÒskiego-Konstytucyjna", 2.4f, 11);
		z.insertOdcinek("Pomorska", "Konstytucyjna-wiadukt", 0.4f, 1);
		z.insertOdcinek("Pomorska", "Wiadukt-CKD SZPITAL", 0.4f, 2);
		z.insertOdcinek("Dzia≥ki", "Wiadukt-TELEFONICZNA ZAJEZDNIA", 0.7f, 3);
		z.insertOdcinek("Telefoniczna", "TELEFONICZNA ZAJEZDNIA-STOKI", 1.7f, 8);
		z.insertOdcinek("Zdrowie", "ZDROWIE-Konstantynowska", 0.3f, 1);
		z.insertOdcinek("Konstantynowska", "Zdrowie-W≥Ûkniarzy", 1.4f, 5);
		z.insertOdcinek("LegionÛw", "W≥Ûkniarzy-Zielona", 0.2f, 1);
		z.insertOdcinek("LegionÛw", "Zielona-Cmentarna", 1.2f, 5);
		z.insertOdcinek("Zielona", "LegionÛw-GdaÒska", 1.5f, 7);
		z.insertOdcinek("GdaÒska", "Zielona-LegionÛw", 0.7f, 3);
		z.insertOdcinek("Zachodnia", "Zielona-LegionÛw", 0.7f, 3);
		z.insertOdcinek("Zielona", "GdaÒska-Koúciuszki", 0.3f, 2);
		z.insertOdcinek("Narutowicza", "Zachodnia-KiliÒskiego", 0.7f, 4);
		z.insertOdcinek("KiliÒskiego", "Narutowicza-Pomorska", 0.7f, 4);
		z.insertOdcinek("Narutowicza", "KiliÒskiego-P.O.W.", 0.25f, 1);
		z.insertOdcinek("NowowÍglowa", "KiliÒskiego-P.O.W.", 0.25f, 1);
		z.insertOdcinek("P.O.W.", "NowowÍglowa-Narutowicza", 0.2f, 1);
		z.insertOdcinek("NowowÍglowa", "P.O.W.-Tramwajowa", 0.7f, 3); //46->44
		z.insertOdcinek("Narutowicza", "P.O.W.-Tramwajowa", 0.7f, 3);
		z.insertOdcinek("Tramwajowa", "NowowÍglowa-Narutowicza", 0.2f, 1);
		z.insertOdcinek("NowowÍglowa", "Tramwajowa-KopciÒskiego", 0.45f, 2);
		z.insertOdcinek("Narutowicza", "Tramwajowa-KopciÒskiego", 0.45f, 2);
		z.insertOdcinek("Narutowicza", "KopciÒskiego-RADIOSTACJA", 0.9f, 3);
		z.insertOdcinek("Konstytucyjna", "RADIOSTACJA-Pomorska", 0.45f, 1);
		z.insertOdcinek("W≥Ûkniarzy", "LegionÛw-Kopernika", 1.5f, 3);
		z.insertOdcinek("W≥Ûkniarzy", "Kopernika-Mickiewicza", 0.1f, 1);
		z.insertOdcinek("Kopernika", "W≥Ûkniarzy-Øeromskiego", 1.1f, 6);
		z.insertOdcinek("GdaÒska", "Øeromskiego-Zielona", 1, 4);
		z.insertOdcinek("Koúciuszki", "Mickiewicza-Zielona", 1.3f, 6);
		z.insertOdcinek("KiliÒskiego", "Narutowicza-NowowÍglowa", 0.3f, 1);
		z.insertOdcinek("KiliÒskiego", "NowowÍglowa-Pi≥sudskiego", 1, 5);
		z.insertOdcinek("KopciÒskiego", "Pi≥sudskiego-NowowÍglowa", 0.7f, 2);
		z.insertOdcinek("Øeromskiego", "WrÛblewskiego-Kopernika", 2, 9);
		z.insertOdcinek("WyszyÒskiego", "WYSZY—SKIEGO-BRATYS£AWSKA", 2.7f, 8);
		z.insertOdcinek("Bratys≥awska-Bandurskiego", "BRATYS£AWSKA-W≥Ûkniarzy", 1.6f, 4);
		z.insertOdcinek("Mickiewicza", "W≥Ûkniarzy-Koúciuszki", 1.5f, 5);
		z.insertOdcinek("Mickiewicza", "Koúciuszki-Piotrkowska", 0.2f, 1);
		z.insertOdcinek("Piotrkowska", "Øwirki-Pi≥sudskiego", 0.4f, 2);
		z.insertOdcinek("Øwirki", "Piotrkowska-Mickiewicza", 0.4f, 2);
		z.insertOdcinek("Pi≥sudskiego", "Piotrkowska-KiliÒskiego", 0.7f, 3);
		z.insertOdcinek("Pi≥sudskiego", "KiliÒskiego-KopciÒskiego", 1.1f, 4);
		z.insertOdcinek("Pi≥sudskiego", "KopciÒskiego-WIDZEW STADION", 2.3f, 6);
		z.insertOdcinek("RokiciÒska", "WIDZEW STADION-Puszkina", 1.3f, 4);
		z.insertOdcinek("RokiciÒska", "Puszkina-WIDZEW AUGUST”W", 1.2f, 2);
		z.insertOdcinek("RokiciÒska-HetmaÒska-Odnowiciela-Al.Ofiar Terroryzmu 11 Wrzeúnia", "WIDZEW AUGUST”W-OLECH”W", 4.5f, 11);
		z.insertOdcinek("Politechniki", "RLL-WrÛblewskiego", 1.4f, 5);
		z.insertOdcinek("WrÛblewskiego-WÛlczaÒska-Czerwona", "Politechniki-Piotrkowska", 0.8f, 5);
		z.insertOdcinek("Piotrkowska", "Czerwona-Øwirki", 1.1f, 5);//74
		z.insertOdcinek("Piotrkowska", "Przybyszewskiego-Czerwona", 0.35f, 1);
		z.insertOdcinek("Piotrkowska", "Przybyszewskiego-PLAC NIEPODLEG£OåCI", 0.35f, 1);
		z.insertOdcinek("KiliÒskiego", "Przybyszewskiego-Pi≥sudskiego", 1.7f, 6);
		z.insertOdcinek("åmig≥ego-Rydza", "Przybyszewskiego-Pi≥sudskiego", 1.6f, 6);
		z.insertOdcinek("Puszkina", "Lodowa-RokiciÒska", 1.7f, 6);
		z.insertOdcinek("Przybyszewskiego", "Piotrkowska-KiliÒskiego", 1, 4);
		z.insertOdcinek("Przybyszewskiego", "KiliÒskiego-åmig≥ego-Rydza", 1, 5);
		z.insertOdcinek("Przybyszewskiego", "åmig≥ego-Rydza-Lodowa", 2.2f, 8);
		z.insertOdcinek("Lodowa", "Przybyszewskiego-CM. ZARZEW", 0.25f, 2);
		z.insertOdcinek("KiliÒskiego", "Dπbrowskiego-Przybyszewskiego", 0.8f, 3);
		z.insertOdcinek("åmig≥ego-Rydza", "Dπbrowskiego-Przybyszewskiego", 1.1f, 3);
		z.insertOdcinek("Rzgowska", "Dπbrowskiego-PL. NIEPODLEG£OåCI", 0.35f, 2);
		z.insertOdcinek("Dπbrowskiego", "Rzgowska-KiliÒskiego", 0.8f, 3);
		z.insertOdcinek("Dπbrowskiego", "KiliÒskiego-åmig≥ego-Rydza", 0.7f, 3);
		z.insertOdcinek("Dπbrowskiego", "åmig≥ego-Rydza-DW. £”Dè D•BROWA", 2.1f, 5);
		z.insertOdcinek("Pabianicka", "RLL-PLAC NIEPODLEG£OåCI", 1.1f, 5);
		z.insertOdcinek("Pabianicka", "ZAJ.CHOCIANOWICE-RLL", 3.2f, 10);
		z.insertOdcinek("Paderewskiego", "RLL-Rzgowska", 1.8f, 7);
		z.insertOdcinek("Rzgowska", "Paderewskiego-Dπbrowskiego", 1, 5);
		z.insertOdcinek("Broniewskiego", "Rzgowska-KiliÒskiego", 0.25f, 2);
		z.insertOdcinek("KiliÒskiego", "Broniewskiego-Dπbrowskiego", 0.7f, 2);
		z.insertOdcinek("KiliÒskiego", "DW.£”Dè CHOJNY-Broniewskiego", 0.5f, 2);
		z.insertOdcinek("åmig≥ego-Rydza", "Broniewskiego-Dπbrowskiego", 0.5f, 4);
		z.insertOdcinek("Rzgowska", "Paderewskiego-CHOJNY KURCZAKI", 1.5f, 6);
		z.insertOdcinek("Rzgowska", "CHOJNY KURCZAKI-INSTYTUT CZMP", 2.1f, 7);
		z.insertOdcinek("£Ûdzka (Zgierz)", "HELEN”WEK-1 Maja (Zgierz)", 2.1f, 6);
		z.insertOdcinek("1 Maja (Zgierz)", "£Ûdzka (Zgierz)-ZGIERZ(PLAC KILI—SKIEGO)", 0.9f, 5);
		z.insertOdcinek("£Ûdzka (Zgierz)-£Íczycka (Zgierz)", "1 Maja (Zgierz)-OZORK”W TR”JK•T", 15.4f, 45);
		z.insertOdcinek("OzorkÛw", "OZORK”W TR”JK•T-OZORK”W CEGIELNIANA", 1.5f, 4);
		z.insertOdcinek("Konstantynowska", "ZAJEZDNIA MUZEALNA BRUS-Zdrowie", 2.2f, 11);
		z.insertOdcinek("KonstantynÛw", "LUTOMIERSK-KONSTANTYN”W", 7.6f, 32);
		z.insertOdcinek("KsawerÛw", "CHOCIANOWICE IKEA-DUØY SKR T", 4.3f, 12);
		z.insertOdcinek("£aska (Pabianice)-Zamkowa (Pabianice)-Warszawska (Pabianice)-£Ûdzka (Pabianice)", "WIEJSKA (PABIANICE)-DUØY SKR T", 5.2f, 19);
		z.insertOdcinek("KopciÒskiego", "NowowÍglowa-Narutowicza", 0.6f, 2);
		z.insertOdcinek("Strykowska", "STRYKOWSKA-DW.£”Dè MARYSIN", 0.3f, 2);
		z.insertOdcinek("OZORK”W (TR”JK•T)", "pÍtla", 0, 0);
		z.insertOdcinek("ZGIERZ (PLAC KILI—SKIEGO)", "pÍtla", 0, 0);
		z.insertOdcinek("HELEN”WEK (P TLA)", "pÍtla", 0, 0);
		z.insertOdcinek("ZAJ.HELEN”WEK", "pÍtla", 0, 0);
		z.insertOdcinek("KOCHAN”WKA", "pÍtla", 0, 0);
		z.insertOdcinek("TEOFIL”W", "pÍtla", 0, 0);
		z.insertOdcinek("DW. £”Dè ØABIENIEC", "pÍtla", 0, 0);
		z.insertOdcinek("MARYSIN WARSZAWSKA", "pÍtla", 0, 0);
		z.insertOdcinek("DW. £”Dè MARYSIN", "pÍtla", 0, 0);
		z.insertOdcinek("DO£Y", "pÍtla", 0, 0);
		z.insertOdcinek("LUTOMIERSK", "pÍtla", 0, 0);
		z.insertOdcinek("KONSTANTYN”W £”DZKI", "pÍtla", 0, 0);
		z.insertOdcinek("ZDROWIE", "pÍtla", 0, 0);
		z.insertOdcinek("KOZINY", "pÍtla", 0, 0);
		z.insertOdcinek("W£”KNIARZY LEGION”W", "pÍtla", 0, 0);
		z.insertOdcinek("P”£NOCNA", "pÍtla", 0, 0);
		z.insertOdcinek("PLAC WOLNOåCI", "pÍtla", 0, 0);
		z.insertOdcinek("ZAJ.TELEFONICZNA", "pÍtla", 0, 0);
		z.insertOdcinek("STOKI", "pÍtla", 0, 0);
		z.insertOdcinek("TELEFONICZNA ZAJEZDNIA", "pÍtla", 0, 0);
		z.insertOdcinek("CKD SZPITAL", "pÍtla", 0, 0);
		z.insertOdcinek("RADIOSTACJA", "pÍtla", 0, 0);
		z.insertOdcinek("DW. £”Dè FABRYCZNA", "pÍtla", 0, 0);
		z.insertOdcinek("RETKINIA", "pÍtla", 0, 0);
		z.insertOdcinek("KAROLEW", "pÍtla", 0, 0);
		z.insertOdcinek("PIOTRKOWSKA CENTRUM", "pÍtla", 0, 0);
		z.insertOdcinek("WIDZEW STADION", "pÍtla", 0, 0);
		z.insertOdcinek("WIDZEW AUGUST”W", "pÍtla", 0, 0);
		z.insertOdcinek("CM. ZARZEW", "pÍtla", 0, 0);
		z.insertOdcinek("OLECH”W", "pÍtla", 0, 0);
		z.insertOdcinek("PL. NIEPODLEG£OåCI", "pÍtla", 0, 0);
		z.insertOdcinek("DW. £”Dè D•BROWA", "pÍtla", 0, 0);
		z.insertOdcinek("R. LOTN. LWOWSKICH", "pÍtla", 0, 0);
		z.insertOdcinek("DW.£”Dè CHOJNY", "pÍtla", 0, 0);
		z.insertOdcinek("D•BROWA NIØSZA", "pÍtla", 0, 0);
		z.insertOdcinek("ZAJ.CHOCIANOWICE", "pÍtla", 0, 0);
		z.insertOdcinek("CHOCIANOWICE IKEA", "pÍtla", 0, 0);
		z.insertOdcinek("DUØY SKR T", "pÍtla", 0, 0);
		z.insertOdcinek("PABIANICE (WIEJSKA)", "pÍtla", 0, 0);
		z.insertOdcinek("CHOJNY KURCZAKI", "pÍtla", 0, 0);
		z.insertOdcinek("INSTYTUT CZMP", "pÍtla", 0, 0);
		z.insertOdcinek("OZORK”W (CEGIELNIANA)", "pÍtla", 0, 0);
		z.insertOdcinek("Broniewskiego", "KiliÒskiego-Niøsza", 0.7f, 2);
		z.insertOdcinek("Niøsza", "D•BROWA NIØSZA-Broniewskiego", 0.5f, 4);
		z.insertOdcinek("Al.Ofiar Terroryzmu 11 Wrzeúnia-Odnowiciela-HetmaÒska-RokiciÒska", "WIDZEW AUGUST”W-OLECH”W", 4.5f, 11);
		z.insertOdcinek("Konstantynowska", "KONSTANTYN”W-ZAJEZDNIA MUZEALNA BRUS", 4.8f, 18);
		z.insertOdcinek("ZAJEZDNIA MUZEALNA BRUS", "pÍtla", 0, 0);	
		z.insertOdcinek("Pabianicka", "CHOCIANOWICE IKEA-ZAJ.CHOCIANOWICE", 1.1f, 4);
		z.insertOdcinek("PÛ≥nocna", "Nowomiejska-KiliÒskiego", 0.5f, 2);
	}
}
