insertStawka("2x805Na", 13.48);
insertStawka("1x805Na", 8.76);
insertStawka("Niskopod≥ogowy", 16.78);
insertStawka("Helmut", 8.56);
insertOdcinek("Aleksandrowska", "CHOCHO£A-TEOFIL”W", 0.8f, 4);
insertOdcinek("Aleksandrowska", "TEOFIL”W-DW.£”Dè ØABIENIEC", 3, 11);
insertOdcinek("Limanowskiego", "DW.£”Dè ØABIENIEC-W≥Ûkniarzy", 0.8f, 1);
insertOdcinek("Limanowskiego", "W≥Ûkniarzy-Zachodnia", 2, 8);
insertOdcinek("Zgierska", "Targowisko Dolna-HELEN”WEK", 4.7f, 16);
insertOdcinek("Warszawska", "Targowisko Dolna-WYCIECZKOWA", 4, 17);
insertOdcinek("Zachodnia", "Limanowskiego-Targowisko Dolna", 0.35f, 2);
insertOdcinek("Zgierska", "Limanowskiego-Targowiska Dolna", 0.45f, 2);
insertOdcinek("Limanowskiego", "Zachodnia-Zgierska", 0.2f, 2);
insertOdcinek("W≥Ûkniarzy", "SrebrzyÒska-Limanowskiego", 2.2f, 7);
insertOdcinek("W≥Ûkniarzy", "LegionÛw-SrebrzyÒska", 0.5f, 2);
insertOdcinek("Zachodnia", "Ogrodowa-Limanowskiego", 1, 5);
insertOdcinek("Zgierska", "Wojska Polskiego-Limanowskiego", 0.35f, 2);
insertOdcinek("Nowomiejska", "PLAC WOLNOåCI-Wojska Polskiego", 0.75f, 6);
insertOdcinek("Wojska Polskiego", "Zgierska-FranciszkaÒska", 0.5f, 2);
insertOdcinek("Wojska Polskiego", "FranciszkaÒska-STRYKOWSKA", 2.7f, 10);
insertOdcinek("FranciszkaÒska", "PÛ≥nocna-Wojska Polskiego", 0.55f, 2);
insertOdcinek("Ogrodowa", "Zachodnia-Nowomiejska", 0.15f, 1);
insertOdcinek("Zachodnia", "LegionÛw-Ogrodowa", 0.25f, 1);
insertOdcinek("KiliÒskiego", "Pomorska-PÛ≥nocna", 0.25f, 2);
insertOdcinek("SrebrzyÒska-Cmentarna", "KOZINY-LegionÛw", 1.5f, 5);
insertOdcinek("LegionÛw", "Cmentarna-GdaÒska", 0.3f, 2);
insertOdcinek("LegionÛw", "GdaÒska-Zachodnia", 0.3f, 2);
insertOdcinek("LegionÛw", "Zachodnia-PLAC WOLNOåCI", 0.2f, 1);
insertOdcinek("Pomorska", "PLAC WOLNOåCI-KiliÒskiego", 0.5f, 3);
insertOdcinek("Pomorska", "KiliÒskiego-Konstytucyjna", 2.4f, 11);
insertOdcinek("Pomorska", "Konstytucyjna-wiadukt", 0.4f, 1);
insertOdcinek("Pomorska", "Wiadukt-CKD", 0.4f, 2);
insertOdcinek("Dzia≥ki", "Wiadukt-TELEFONICZNA", 0.7f, 3);
insertOdcinek("Telefoniczna", "TELEFONICZNA-STOKI", 1.7f, 8);
insertOdcinek("Zdrowie", "ZDROWIE-Konstantynowska", 0.3f, 1);
insertOdcinek("Konstantynowska", "Zdrowie-W≥Ûkniarzy", 1.4f, 5);
insertOdcinek("LegionÛw", "W≥Ûkniarzy-Zielona", 0.2f, 1);
insertOdcinek("LegionÛw", "Zielona-Cmentarna", 1.2f, 5);
insertOdcinek("Zielona", "LegionÛw-GdaÒska", 1.5f, 7);
insertOdcinek("GdaÒska", "Zielona-LegionÛw", 0.7f, 3);
insertOdcinek("Zachodnia", "Zielona-LegionÛw", 0.7f, 3);
insertOdcinek("Zielona", "GdaÒska-Koúciuszki", 0.3f, 2);
insertOdcinek("Narutowicza", "Zachodnia-KiliÒskiego", 0.7f, 4);
insertOdcinek("KiliÒskiego", "Narutowicza-Pomorska", 0.7f, 4);
insertOdcinek("Narutowicza", "KiliÒskiego-P.O.W.", 0.25f, 1);
insertOdcinek("NowowÍglowa", "KiliÒskiego-P.O.W.", 0.25f, 1);
insertOdcinek("P.O.W.", "NowowÍglowa-Narutowicza", 0.2f, 1);
insertOdcinek("NowowÍglowa", "P.O.W.-Tramwajowa", 0.7f, 3); //46->44
insertOdcinek("Narutowicza", "P.O.W.-Tramwajowa", 0.7f, 3);
insertOdcinek("Tramwajowa", "NowowÍglowa-Narutowicza", 0.2f, 1);
insertOdcinek("NowowÍglowa", "Tramwajowa-KopciÒskiego", 0.45f, 2);
insertOdcinek("Narutowicza", "Tramwajowa-KopciÒskiego", 0.45f, 2);
insertOdcinek("Narutowicza", "KopciÒskiego-RADIOSTACJA", 0.9f, 3);
insertOdcinek("Konstytucyjna", "RADIOSTACJA-Pomorska", 0.45f, 1);
insertOdcinek("W≥Ûkniarzy", "LegionÛw-Kopernika", 1.5f, 3);
insertOdcinek("W≥Ûkniarzy", "Kopernika-Mickiewicza", 0.1f, 1);
insertOdcinek("Kopernika", "W≥Ûkniarzy-Øeromskiego", 1.1f, 6);
insertOdcinek("GdaÒska", "Øeromskiego-Zielona", 1, 4);
insertOdcinek("Koúciuszki", "Mickiewicza-Zielona", 1.3f, 6);
insertOdcinek("KiliÒskiego", "Narutowicza-NowowÍglowa", 0.3f, 1);
insertOdcinek("KiliÒskiego", "NowowÍglowa-Pi≥sudskiego", 1, 5);
insertOdcinek("KopciÒskiego", "Pi≥sudskiego-NowowÍglowa", 0.7f, 2);
insertOdcinek("Øeromskiego", "WrÛblewskiego-Kopernika", 2, 9);
insertOdcinek("WyszyÒskiego", "WYSZY—SKIEGO-BRATYS£AWSKA", 2.7f, 8);
insertOdcinek("Bratys≥awska-Bandurskiego", "BRATYS£AWSKA-W≥Ûkniarzy", 1.6f, 4);
insertOdcinek("Mickiewicza", "W≥Ûkniarzy-Koúciuszki", 1.5f, 5);
insertOdcinek("Mickiewicza", "Koúciuszki-Piotrkowska", 0.2f, 1);
insertOdcinek("Piotrkowska", "Øwirki-Pi≥sudskiego", 0.4f, 2);
insertOdcinek("Øwirki", "Piotrkowska-Mickiewicza", 0.4f, 2);
insertOdcinek("Pi≥sudskiego", "Piotrkowska-KiliÒskiego", 0.7f, 3);
insertOdcinek("Pi≥sudskiego", "KiliÒskiego-KopciÒskiego", 1.1f, 4);
insertOdcinek("Pi≥sudskiego", "KopciÒskiego-WIDZEW STADION", 2.3f, 6);
insertOdcinek("RokiciÒska", "WIDZEW STADION-Puszkina", 1.3f, 4);
insertOdcinek("RokiciÒska", "Puszkina-AUGUST”W", 1.2f, 2);
insertOdcinek("RokiciÒska-HetmaÒska-Odnowiciela-Al.Ofiar Terroryzmu 11 Wrzeúnia", "AUGUST”W-OLECH”W", 4.5f, 11);
insertOdcinek("Politechniki", "RLL-WrÛblewskiego", 1.4f, 5);
insertOdcinek("WrÛblewskiego-WÛlczaÒska-Czerwona", "Politechniki-Piotrkowska", 0.8f, 5);
insertOdcinek("Piotrkowska", "Czerwona-Øwirki", 1.1f, 5);//74
insertOdcinek("Piotrkowska", "Przybyszewskiego-Czerwona", 0.35f, 1);
insertOdcinek("Piotrkowska", "Przybyszewskiego-PLAC NIEPODLEG£OåCI", 0.35f, 1);
insertOdcinek("KiliÒskiego", "Przybyszewskiego-Pi≥sudskiego", 1.7f, 6);
insertOdcinek("åmig≥ego-Rydza", "Przybyszewskiego-Pi≥sudskiego", 1.6f, 6);
insertOdcinek("Puszkina", "Lodowa-RokiciÒska", 1.7f, 6);
insertOdcinek("Przybyszewskiego", "Piotrkowska-KiliÒskiego", 1, 4);
insertOdcinek("Przybyszewskiego", "KiliÒskiego-åmig≥ego-Rydza", 1, 5);
insertOdcinek("Przybyszewskiego", "åmig≥ego-Rydza-Lodowa", 2.2f, 8);
insertOdcinek("Lodowa", "Przybyszewskiego-CM. ZARZEW", 0.25f, 2);
insertOdcinek("KiliÒskiego", "Dπbrowskiego-Przybyszewskiego", 0.8f, 3);
insertOdcinek("åmig≥ego-Rydza", "Dπbrowskiego-Przybyszewskiego", 1.1f, 3);
insertOdcinek("Rzgowska", "Dπbrowskiego-PL. NIEPODLEG£OåCI", 0.35f, 2);
insertOdcinek("Dπbrowskiego", "Rzgowska-KiliÒskiego", 0.8f, 3);
insertOdcinek("Dπbrowskiego", "KiliÒskiego-åmig≥ego-Rydza", 0.7f, 3);
insertOdcinek("Dπbrowskiego", "åmig≥ego-Rydza-D•BROWA", 2.1f, 5);
insertOdcinek("Pabianicka", "RLL-PLAC NIEPODLEG£OåCI", 1.1f, 5);
insertOdcinek("Pabianicka", "ZAJ.CHOCIANOWICE-RLL", 3.2f, 10);
insertOdcinek("Paderewskiego", "RLL-Rzgowska", 1.8f, 7);
insertOdcinek("Rzgowska", "Paderewskiego-Dπbrowskiego", 1, 5);
insertOdcinek("Broniewskiego", "Rzgowska-KiliÒskiego", 0.25f, 2);
insertOdcinek("KiliÒskiego", "Broniewskiego-Dπbrowskiego", 0.7f, 2);
insertOdcinek("KiliÒskiego", "DW.£”Dè CHOJNY-Broniewskiego", 0.5f, 2);
insertOdcinek("åmig≥ego-Rydza", "Broniewskiego-Dπbrowskiego", 0.5f, 4);
insertOdcinek("Rzgowska", "Paderewskiego-KURCZAKI", 1.5f, 6);
insertOdcinek("Rzgowska", "KURCZAKI-SZPITAL CZMP", 2.1f, 7);
insertOdcinek("£Ûdzka (Zgierz)", "HELEN”WEK-1 Maja (Zgierz)", 2.1f, 6);
insertOdcinek("1 Maja (Zgierz)", "£Ûdzka (Zgierz)-ZGIERZ(PLAC KILI—SKIEGO)", 0.9f, 5);
insertOdcinek("£Ûdzka (Zgierz)-£Íczycka (Zgierz)", "1 Maja (Zgierz)-OZORK”W TR”JK•T", 15.4f, 45);
insertOdcinek("OzorkÛw", "OZORK”W TR”JK•T-OZORK”W CEGIELNIANA", 1.5f, 4);
insertOdcinek("Konstantynowska", "ZAJ.BRUS-Zdrowie", 2.2f, 11);
insertOdcinek("KonstantynÛw", "LUTOMIERSK-KONSTANTYN”W", 7.6f, 32);
insertOdcinek("KsawerÛw", "CHOCIANOWICE IKEA-DUØY SKR T", 4.3f, 12);
insertOdcinek("£aska (Pabianice)-Zamkowa (Pabianice)-Warszawska (Pabianice)-£Ûdzka (Pabianice)", "WIEJSKA (PABIANICE)-DUØY SKR T", 5.2f, 19);
insertOdcinek("KopciÒskiego", "NowowÍglowa-Narutowicza", 0.6f, 2);
insertOdcinek("Strykowska", "STRYKOWSKA-DW.£”Dè MARYSIN", 0.3f, 2);
insertOdcinek("OZORK”W (TR”JK•T)", "pÍtla", 0, 0);
insertOdcinek("ZGIERZ (PLAC KILI—SKIEGO)", "pÍtla", 0, 0);
insertOdcinek("HELEN”WEK (P TLA)", "pÍtla", 0, 0);
insertOdcinek("ZAJ.HELEN”WEK", "pÍtla", 0, 0);
insertOdcinek("CHOCHO£A", "pÍtla", 0, 0);
insertOdcinek("TEOFIL”W", "pÍtla", 0, 0);
insertOdcinek("DW. £”Dè ØABIENIEC", "pÍtla", 0, 0);
insertOdcinek("WYCIECZKOWA", "pÍtla", 0, 0);
insertOdcinek("DW. £”Dè MARYSIN", "pÍtla", 0, 0);
insertOdcinek("DO£Y", "pÍtla", 0, 0);
insertOdcinek("LUTOMIERSK", "pÍtla", 0, 0);
insertOdcinek("KONSTANTYN”W £”DZKI", "pÍtla", 0, 0);
insertOdcinek("ZDROWIE", "pÍtla", 0, 0);
insertOdcinek("KOZINY", "pÍtla", 0, 0);
insertOdcinek("LEGION”W", "pÍtla", 0, 0);
insertOdcinek("P”£NOCNA", "pÍtla", 0, 0);
insertOdcinek("PLAC WOLNOåCI", "pÍtla", 0, 0);
insertOdcinek("ZAJ.TELEFONICZNA", "pÍtla", 0, 0);
insertOdcinek("STOKI", "pÍtla", 0, 0);
insertOdcinek("TELEFONICZNA", "pÍtla", 0, 0);
insertOdcinek("CKD", "pÍtla", 0, 0);
insertOdcinek("RADIOSTACJA", "pÍtla", 0, 0);
insertOdcinek("DW. £”Dè FABRYCZNA", "pÍtla", 0, 0);
insertOdcinek("RETKINIA", "pÍtla", 0, 0);
insertOdcinek("KAROLEW", "pÍtla", 0, 0);
insertOdcinek("PIOTRKOWSKA CENTRUM", "pÍtla", 0, 0);
insertOdcinek("WIDZEW STADION", "pÍtla", 0, 0);
insertOdcinek("AUGUST”W", "pÍtla", 0, 0);
insertOdcinek("CM. ZARZEW", "pÍtla", 0, 0);
insertOdcinek("OLECH”W", "pÍtla", 0, 0);
insertOdcinek("PL. NIEPODLEG£OåCI", "pÍtla", 0, 0);
insertOdcinek("D•BROWA", "pÍtla", 0, 0);
insertOdcinek("RONDO LOTNIK”W LWOWSKICH", "pÍtla", 0, 0);
insertOdcinek("DW.£”Dè CHOJNY", "pÍtla", 0, 0);
insertOdcinek("åL•SKA", "pÍtla", 0, 0);
insertOdcinek("ZAJ.CHOCIANOWICE", "pÍtla", 0, 0);
insertOdcinek("CHOCIANOWICE IKEA", "pÍtla", 0, 0);
insertOdcinek("DUØY SKR T", "pÍtla", 0, 0);
insertOdcinek("PABIANICE (WIEJSKA)", "pÍtla", 0, 0);
insertOdcinek("KURCZAKI", "pÍtla", 0, 0);
insertOdcinek("SZPITAL CZMP", "pÍtla", 0, 0);
insertOdcinek("OZORK”W (CEGIELNIANA)", "pÍtla", 0, 0);
insertOdcinek("Broniewskiego", "KiliÒskiego-Niøsza", 0.7f, 2);
insertOdcinek("Niøsza", "åL•SKA-Broniewskiego", 0.5f, 4);
insertOdcinek("Al.Ofiar Terroryzmu 11 Wrzeúnia-Odnowiciela-HetmaÒska-RokiciÒska", "AUGUST”W-OLECH”W", 4.5f, 11);
insertOdcinek("Konstantynowska", "KONSTANTYN”W-ZAJ.BRUS", 4.8f, 18);
insertOdcinek("ZAJ. MUZEALNA BRUS", "pÍtla", 0, 0);	
insertOdcinek("Pabianicka", "CHOCIANOWICE IKEA-ZAJ.CHOCIANOWICE", 1.1f, 4);
insertOdcinek("PÛ≥nocna", "Nowomiejska-KiliÒskiego", 0.5f, 2);